# define the two containers
services:
  db-psql:
    # pull the postgres image from DockerHub
    image: postgres:16
    container_name: db-psql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db-volume:/var/lib/postgresql/data
    healthcheck:
      # used in flask container depends_on condition to wait for the DB to be ready
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 20s
      retries: 5


  web-app:
    #build: .
    image: ghcr.io/ttala/carshop-api:latest
    container_name: carshop
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL} 
    depends_on:
      db-psql:
        # waiting for the database to be ready
        condition: service_healthy
    volumes:
      - .:/app

volumes:
  # to persist the database tables
  db-volume: